
import Footer from './Components/shared/Footer'
import Header from './Components/shared/Header'
import './globals.css'
import { Inter,Sen } from 'next/font/google'

const inter = Inter({ subsets: ['latin'],variable:"--inter" })
 const sen= Sen({
   weight:[ '400' ,'700','800'],
  variable: "--sen",
  subsets:['latin'],
  style:['normal'],
  display:'swap',




})
 

export const metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sen.variable} ${inter.variable}`}>
        <Header />
        
        {children}
        <Footer /> 
        
        </body>
    </html>
  )
}
